# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-22 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cost_price', models.FloatField()),
                ('selling_price', models.IntegerField()),
                ('stocks', models.IntegerField()),
                ('totalcp', models.FloatField()),
                ('totalsp', models.IntegerField()),
                ('assumed_profit', models.FloatField()),
                ('left_amount', models.FloatField()),
                ('exipry_date', models.DateField()),
                ('added_date', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=300)),
            ],
        ),
    ]
