# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-22 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_cart_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_price', models.IntegerField()),
                ('profit_or_loss', models.FloatField()),
                ('sold_on', models.DateField(auto_now_add=True)),
                ('remark', models.CharField(max_length=10)),
                ('total_amount', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
            ],
        ),
    ]
