# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-23 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='quantity',
            field=models.IntegerField(default=None),
        ),
    ]
